version: "3.9"

services:
  postgresql:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=peanodejs
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=peanodejs
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "54326:5432"